### ISSUE TITLE
Cannot install perses > 0.8.1 with python > 3.7 because of pymbar

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/perses#923] opened 2022-01-21 18:56 UTC
If my conda environment has python > 3.8, running `mamba install -c conda-forge perses` will install `perses 0.8.1`.

If I try to install a more recent version of perses,  running `mamba install -c conda-forge --only-deps perses=0.9.1`:
```
Problem: package perses-0.9.1-pyh8a188c0_0 requires pymbar 3.0.3, but none of the providers can be installed
```
which is because pymbar 3.0.3 requires python >=3.7,<3.8.0a0.

We are requiring the older version of pymbar (3.0.3) because of https://github.com/choderalab/pymbar/issues/419.

Possible solutions:
- get a bugfix release of pymbar out asap (so that we don't have to rely on the older version of pymbar)
- update pymbar 3.0.3 to support newer versions of python.

**Comment by mikemhenry** [comment] 2022-01-21 21:22
related:
https://github.com/conda-forge/perses-feedstock/issues/11

**Comment by mikemhenry** [comment] 2022-01-21 21:44
So we can fix this in the pinning in the next release, since our unit tests pass with `pymbar 3.0.5 ` but there could be issues. Can you make an env with perses 0.9.1 or 0.9.2 and pymbar 3.0.5 and run your workflow to make sure there will be no major issues?
You can create the env by using the yaml here https://github.com/choderalab/perses/blob/master/devtools/conda-envs/test_env.yaml then doing a `pip install .`

**Comment by zhang-ivy** [comment] 2022-01-21 22:08
>Can you make an env with perses 0.9.1 or 0.9.2 and pymbar 3.0.5
I already tried this. pymbar 3.0.5 is problematic for analyzing repex simulations (I'm seeing the same issue as reported by the pymbar issue that I linked above).

**Comment by jchodera** [comment] 2022-01-22 02:32
Can you remind me what the issue is with analyzing repex trajectories with
the latest pymbar? I can dive in and help fix that on our end.

**Comment by zhang-ivy** [comment] 2022-01-22 04:16
See details at https://github.com/choderalab/pymbar/issues/419.
To quote Michael Shirts: "for the majority of 3.0.3 -> 3.0.5 issues, the default solver switched (which is good - the "adaptive" solver is much more consistent), but the default maximum number of iterations is too low (250), and thus MBAR doesn't go to completion."

Josh fass's fix here fixed the issue for me: https://github.com/choderalab/pymbar/pull/425

**Comment by ijpulidos** [comment] 2022-01-24 21:08
@mikemhenry will be releasing a new bugfix for pymbar that should solve this issue.

**Comment by mikemhenry** [comment] 2022-01-31 17:58
fixed with https://github.com/conda-forge/pymbar-feedstock/pull/19

**Closed by mikemhenry** 2022-01-31 17:58 UTC
