### ISSUE TITLE
[HybridTopologyFactory] `CustomNonbondedForce` cutoff doesn't match `NonBondedForce`

### ISSUE THREAD

**Issue by IAlibay** [choderalab/perses#1194] opened 2023-05-11 19:41 UTC
If two endstate systems are built with a non-1.0 nm cutoff, the HybridTopologyFactory will set the `NonBondedForce` to that cutoff value, but will leave `CustomNonbondedForce` to its default value of 1.0.

It's unclear if this is an intended feature or a bug. It looks like RestCapableHybridTopologyFactory does add a cutoff to custom_force, but it would be great to also be able to do this in the base class (if possible).

## How to reproduce

A quick way to reproduce is to manually force an `'nonbondedCutoff': 0.9` entry to the SystemGenerator calls in `relative_setup`.

**Comment by IAlibay** [comment] 2023-06-20 18:06
Could I maybe ping this again please? I'm happy to fix this, but I would need to know if it's a feature or a bug.

**Comment by ijpulidos** [comment] 2023-07-24 16:01
Apologies for the delayed response, I don't recall this being an intended behavior, will raise this up in the next perses dev meeting. Thanks for bringing this up.

**Comment by ijpulidos** [comment] 2023-07-25 15:20
This seems like a bug and we should be setting the  `_add_nonbonded_force_terms` for the `HybridTopologyFactory`, we should also add a test for this. Thanks for reporting!

**Comment by ijpulidos** [comment] 2023-09-11 17:40
closed via #1230

**Closed by ijpulidos** 2023-09-11 17:40 UTC
Labels: potential bug :thinking: :bug:, priority: high
